name: Despliegue en servidor de producción

on:
  push:
    branches:
      - main  # Cambiar "main" por el nombre de tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest  # Puedes cambiar "ubuntu-latest" por otra versión de Linux si es necesario

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Instalar dependencias y construir la aplicación
      run: |
        # Instalar dependencias
        npm install
        
        # Construir la aplicación
        npm run build

    - name: Copiar archivos al servidor
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."  # Ruta a los archivos que deseas copiar al servidor
        target: "/ruta/en/tu/servidor"  # Ruta de destino en el servidor

    - name: Ejecutar comandos en el servidor
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Comandos para reiniciar la aplicación en el servidor
          # Por ejemplo, si es una aplicación Node.js:
          # pm2 restart mi_aplicacion