name: Despliegue en servidor de producción

on:
  push:
    branches:
      - main  # Cambiar "main" por el nombre de tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest  # Puedes cambiar "ubuntu-latest" por otra versión de Linux si es necesario

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Ejecutar comandos en el servidor
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/pesvsisi/supertransporte_archivos
          npm install
          npm run build
          cp .env build/.env
          pm2 restart archivos